---
title: "notes"
output: html_document
---

```{r}
fgsea_gtable <- plotGseaTable(
  pathways = msg_list[topPathways],
  stats = ranks,
  fgseaRes = fgsea_results,
  gseaParam = 0.5,
  render = F,
  colwidths = c(70, 10, 8, 12, 12)
)

#fgsea_gtable <- gtable::gtable_add_padding(fgsea_gtable, padding = unit(2, "cm"))

plot(fgsea_gtable)
```


##10x
```{r}
shinyApp(
  ui = fluidPage(
      titlePanel("10x QC"),
  
      sidebarLayout(
          sidebarPanel(
              selectInput(inputId = 'xcol', label = 'X Variable', choices = levels(as.factor(merged$metricname)))
          ),
  
          mainPanel(
             plotlyOutput("metricBoxplot", height = "400px", width = "600px")
          )
      ),
      actionButton("plotButton", "Plot")
  ),
  
  
  
  server = function(input, output) {
      data <- reactiveValues()
      
      observeEvent(input$plotButton,{
          data$xcol <- input$xcol
          
  
      output$metricBoxplot <- renderPlotly({
          req(data$xcol)  #to delay displaying result until user press Apply 
          plotRange(metricData = merged, metricName = data$xcol)
      })
  })
  }
)
```

##shiny_UI.R
```{r}
##----------------------------------------------------------------------------##
## Custom functions.
##----------------------------------------------------------------------------##
cerebroBox <- function(title, content) {
  box(
    title = title,
    status = "primary",
    solidHeader = TRUE,
    width = 12,
    collapsible = TRUE,
    content
  )
}

cerebroInfoButton <- function(id) {
  actionButton(
    inputId = id,
    label = "info",
    icon = NULL,
    class = "btn-xs",
    title = "Show additional information for this panel."
  )
}

boxTitle <- function(title) {
  p(title, style = "padding-right: 5px; display: inline")
}

##----------------------------------------------------------------------------##
##
##----------------------------------------------------------------------------##
source(system.file("shiny/v1.2/load_data/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/overview/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/samples/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/clusters/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/most_expressed_genes/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/marker_genes/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/enriched_pathways/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/gene_expression/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/gene_set_expression/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/trajectory/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/gene_id_conversion/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/analysis_info/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/color_management/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/about/UI.R", package = "cerebroApp"), local = TRUE)

##----------------------------------------------------------------------------##
##
##----------------------------------------------------------------------------##
ui <- dashboardPage(
  dashboardHeader(
    title = span("Cerebro ", style = "color: white; font-size: 28px; font-weight: bold")
  ),
  dashboardSidebar(
    tags$head(tags$style(HTML(".content-wrapper {overflow-x: scroll;}"))),
    sidebarMenu(
      sidebarMenuOutput("sidebar_menu")
    )
  ),
  dashboardBody(
    tags$script(HTML('$("body").addClass("fixed");')),
    tabItems(
      tab_load_data,
      tab_overview,
      tab_samples,
      tab_clusters,
      tab_most_expressed_genes,
      tab_marker_genes,
      tab_enriched_pathways,
      tab_gene_expression,
      tab_gene_set_expression,
      tab_trajectory,
      tab_gene_id_conversion,
      tab_analysis_info,
      tab_color_management,
      tab_about
    )
  )
)
```


#shiny_server.R
```{r}
##----------------------------------------------------------------------------##
##
##----------------------------------------------------------------------------##
server <- function(input, output, session) {

  ##--------------------------------------------------------------------------##
  ## Color management.
  ##--------------------------------------------------------------------------##
  # Dutch palette from flatuicolors.com
  colorset_dutch <- c(
    "#FFC312","#C4E538","#12CBC4","#FDA7DF","#ED4C67",
    "#F79F1F","#A3CB38","#1289A7","#D980FA","#B53471",
    "#EE5A24","#009432","#0652DD","#9980FA","#833471",
    "#EA2027","#006266","#1B1464","#5758BB","#6F1E51"
  )

  # Spanish palette from flatuicolors.com
  colorset_spanish <- c(
    "#40407a","#706fd3","#f7f1e3","#34ace0","#33d9b2",
    "#2c2c54","#474787","#aaa69d","#227093","#218c74",
    "#ff5252","#ff793f","#d1ccc0","#ffb142","#ffda79",
    "#b33939","#cd6133","#84817a","#cc8e35","#ccae62"
  )

  default_colorset <- c(colorset_dutch, colorset_spanish)

  cell_cycle_colorset <- setNames(
    c("#45aaf2", "#f1c40f", "#e74c3c", "#7f8c8d"),
    c("G1",      "S",       "G2M",     "-")
  )

  ##--------------------------------------------------------------------------##
  ## Central parameters.
  ##--------------------------------------------------------------------------##
  scatter_plot_dot_size <- list(
    min = 1,
    max = 20,
    step = 1,
    default = 5
  )

  scatter_plot_dot_opacity <- list(
    min = 0.1,
    max = 1.0,
    step = 0.1,
    default = 1.0
  )

  scatter_plot_percentage_cells_to_show <- list(
    min = 10,
    max = 100,
    step = 10,
    default = 100
  )

  preferences <- reactiveValues(use_webgl = TRUE)

  ##--------------------------------------------------------------------------##
  ## Sidebar menu.
  ##--------------------------------------------------------------------------##
  output[["sidebar_menu"]] <- renderMenu({
    sidebarMenu(id = "sidebar",
      menuItem(
        "Load data", tabName = "loadData",
        icon = icon("spinner"), selected = TRUE
      ),
      menuItem(
        "Overview", tabName = "overview",
        icon = icon("binoculars")
      ),
      menuItem(
        "Samples", tabName = "samples",
        icon = icon("star")
      ),
      menuItem(
        "Clusters", tabName = "clusters",
        icon = icon("braille")
      ),
      menuItem(
        "Most expressed genes", tabName = "mostExpressedGenes",
        icon = icon("bullhorn")
      ),
      menuItem(
        "Marker genes", tabName = "markerGenes",
        icon = icon("magnet")
      ),
      menuItem(
        "Enriched pathways", tabName = "enrichedPathways",
        icon = icon("sitemap")
      ),
      menuItem(
        "Gene expression", tabName = "geneExpression",
        icon = icon("signal")
      ),
      menuItem(
        "Gene set expression", tabName = "geneSetExpression",
        icon = icon("list")
      ),
      menuItem(
        "Trajectory", tabName = "trajectory",
        icon = icon("random")
      ),
      menuItem(
        "Gene ID conversion", tabName = "geneIdConversion",
        icon = icon("barcode")
      ),
      menuItem(
        "Analysis info", tabName = "info",
        icon = icon("info")
      ),
      menuItem(
        "Color management", tabName = "color_management",
        icon = icon("palette")
      ),
      menuItem(
        "About", tabName = "about",
        icon = icon("at")
      )
    )
  })

  ##--------------------------------------------------------------------------##
  ## Sample data.
  ##--------------------------------------------------------------------------##
  sample_data <- reactive({
    if ( is.null(input[["input_file"]]) || is.na(input[["input_file"]]) ) {
      sample_data <- readRDS(
        system.file("extdata/v1.2/example.rds", package = "cerebroApp")
      )
    } else {
      req(input[["input_file"]])
      sample_data <- readRDS(input[["input_file"]]$datapath)
    }
    # get list of sample names
    if ( is.factor(sample_data$cells$sample) ) {
      sample_data$sample_names <- levels(sample_data$cells$sample)
    } else {
      sample_data$sample_names <- sample_data$cells$sample %>% unique()
    }
    # get list of cluster names
    if ( is.factor(sample_data$cells$cluster) ) {
      sample_data$cluster_names <- levels(sample_data$cells$cluster)
    } else {
      sample_data$cluster_names <- sample_data$cells$cluster %>% unique() %>% sort()
    }
    sample_data
  })

  ##--------------------------------------------------------------------------##
  ## Function to calculate A-by-B tables (e.g. samples by clusters).
  ##--------------------------------------------------------------------------##
  calculateTableAB <- function(groupA, groupB) {
    # check if specified group columns exist in meta data
    if ( groupA %in% colnames(sample_data()$cells) == FALSE ) {
      stop(paste0("Column specified as groupA (`", groupA, "`) could not be found in meta data."), call. = FALSE)
    }
    if ( groupB %in% colnames(sample_data()$cells) == FALSE ) {
      stop(paste0("Column specified as groupB (`", groupB, "`) could not be found in meta data."), call. = FALSE)
    }
    table <- sample_data()$cells[,c(groupA,groupB)]
    # factorize group columns A and B if not already a factor
    if ( is.character(table[,groupA]) ) {
      table[[,groupA]] <- factor(
        table[[,groupA]],
        levels = table[[,groupA]] %>% unique() %>% sort()
      )
    }
    if ( is.character(table[,groupB]) ) {
      table[[,groupB]] <- factor(
        table[[,groupB]],
        levels = table[[,groupB]] %>% unique() %>% sort()
      )
    }
    # generate table
    table <- table %>%
      dplyr::group_by_at(c(groupA,groupB)) %>%
      dplyr::summarize(count = dplyr::n()) %>%
      tidyr::spread(`groupB`, count, fill = 0) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(total_cell_count = rowSums(.[c(2:ncol(.))])) %>%
      dplyr::select(c(`groupA`, 'total_cell_count', dplyr::everything()))
    # fix order of columns if cell cycle info was chosen as second group
    if ( 'G1' %in% colnames(table) && 'G2M' %in% colnames(table) && 'S' %in% colnames(table) ) {
      table <- table %>%
        dplyr::select(c(`groupA`, 'total_cell_count', 'G1', 'S', 'G2M', dplyr::everything()))
    }
    # return
    return(table)
  }

  ##--------------------------------------------------------------------------##
  ## Colors for samples and clusters.
  ##--------------------------------------------------------------------------##
  reactive_colors <- reactive({
    colors <- list()

    # grab sample-specific colors from input file if it exists, otherwise take
    # default colorset
    if ( !is.null(sample_data()$samples$colors) ) {
      colors$samples <- sample_data()$samples$colors
    } else {
      colors$samples <- default_colorset[1:length(sample_data()$sample_names)]
      names(colors$samples) <- sample_data()$sample_names
    }
    # assign respective color picker in "Color management" tab to each sample
    if ( !is.null(input[[paste0('color_sample_', levels(sample_data()$cells$sample)[1])]]) ) {
      for ( i in 1:length(colors$samples) ) {
        colors$samples[i] <- input[[paste0('color_sample_', levels(sample_data()$cells$sample)[i])]]
      }
    }

    # grab cluster-specific colors from input file if it exists, otherwise take
    # default colorset
    if ( !is.null(sample_data()$clusters$colors) ) {
      colors$clusters <- sample_data()$clusters$colors
    } else {
      colors$clusters <- default_colorset[1:length(sample_data()$cluster_names)]
      names(colors$clusters) <- sample_data()$cluster_names
    }
    # assign respective color picker in "Color management" tab to each cluster
    if ( !is.null(input[[paste0('color_cluster_', levels(sample_data()$cells$cluster)[1])]]) ) {
      for ( i in 1:length(colors$clusters) ) {
        colors$clusters[i] <- input[[paste0('color_cluster_', levels(sample_data()$cells$cluster)[i])]]
      }
    }

    return(colors)
  })

  ##--------------------------------------------------------------------------##
  ## Tabs.
  ##--------------------------------------------------------------------------##
  source(system.file("shiny/v1.2/load_data/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/overview/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/samples/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/clusters/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/most_expressed_genes/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/marker_genes/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/enriched_pathways/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/gene_expression/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/gene_set_expression/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/gene_id_conversion/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/trajectory/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/analysis_info/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/color_management/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/about/server.R", package = "cerebroApp"), local = TRUE)

}
```


##uiOutput
```{r}

# UI element: choose source for pathway enrichement results (currently Enrichr or GSVA)
output[["enriched_pathways_by_sample_select_source_UI"]] <- renderUI({
  if ( is.null(sample_data()$enriched_pathways) ) {
    textOutput("enriched_pathways_by_sample_table_missing")
  } else {
    selectInput(
      "enriched_pathways_by_sample_select_source",
      label = NULL,
      choices = names(sample_data()$enriched_pathways)
    )
  }
})

# UI element: display results or alternative text
output[["enriched_pathways_by_sample_UI"]] <- renderUI({
  req(input[["enriched_pathways_by_sample_select_source"]])
  if ( input[["enriched_pathways_by_sample_select_source"]] == "enrichr" ) {
    if ( !is.null(sample_data()$enriched_pathways$enrichr$by_sample) ) {
      if ( is.list(sample_data()$enriched_pathways$enrichr$by_sample) ) {
        tagList(
          fluidRow(
            column(4,
              uiOutput("enriched_pathways_by_sample_select_sample_UI")
            ),
            column(8,
              uiOutput("enriched_pathways_by_sample_select_db_UI")
            )
          ),
          DT::dataTableOutput("enriched_pathways_by_sample_table_present")
        )
      } else if ( sample_data()$enriched_pathways$enrichr$by_sample == "no_markers_found" ) {
        textOutput("enriched_pathways_by_sample_table_no_markers_found")
      }
    } else {
      textOutput("enriched_pathways_by_sample_table_missing_enrichr")
    }
  } else if ( input[["enriched_pathways_by_sample_select_source"]] == "GSVA" ) {
    if ( !is.null(sample_data()$enriched_pathways$GSVA$by_sample) ) {
      if ( is.data.frame(sample_data()$enriched_pathways$GSVA$by_sample) ) {
        tagList(
          fluidRow(
            column(4,
              uiOutput("enriched_pathways_by_sample_select_sample_UI")
            )
          ),
          DT::dataTableOutput("enriched_pathways_by_sample_table_present")
        )
      } else if ( sample_data()$enriched_pathways$GSVA$by_sample == "no_gene_sets_enriched" ) {
        textOutput("enriched_pathways_by_sample_table_no_gene_sets_enriched")
      } else if ( sample_data()$enriched_pathways$GSVA$by_sample == "only_one_sample_in_data_set" ) {
        textOutput("enriched_pathways_by_sample_table_only_one_sample_in_data_set")
      }
    } else {
      textOutput("enriched_pathways_by_sample_table_missing_gsva")
    }
  }
})

# UI element: choose sample
output[["enriched_pathways_by_sample_select_sample_UI"]] <- renderUI({
  req(input[["enriched_pathways_by_sample_select_source"]])
  if ( input[["enriched_pathways_by_sample_select_source"]] == 'enrichr' ) {
    choices <- levels(sample_data()$enriched_pathways$enrichr$by_sample$sample) %>%
      intersect(., unique(sample_data()$enriched_pathways$enrichr$by_sample$sample))
  } else if ( input[["enriched_pathways_by_sample_select_source"]] == 'GSVA' ) {
    choices <- levels(sample_data()$enriched_pathways$GSVA$by_sample$group) %>%
      intersect(., unique(sample_data()$enriched_pathways$GSVA$by_sample$group))
  }
  selectInput(
    "enriched_pathways_by_sample_select_sample",
    label = NULL,
    choices = choices
  )
})

# UI element: choose database
output[["enriched_pathways_by_sample_select_db_UI"]] <- renderUI({
  req(
    input[["enriched_pathways_by_sample_select_source"]],
    input[["enriched_pathways_by_sample_select_sample"]]
  )
  choices <- sample_data()$enriched_pathways$enrichr$by_sample %>%
    dplyr::filter(sample == input[["enriched_pathways_by_sample_select_sample"]]) %>%
    dplyr::pull(db) %>%
    intersect(., levels(.))
  selectInput(
    "enriched_pathways_by_sample_select_db",
    label = NULL,
    choices = choices
  )
})

# table
output[["enriched_pathways_by_sample_table_present"]] <- DT::renderDataTable(server = FALSE, {
  req(
    input[["enriched_pathways_by_sample_select_source"]],
    input[["enriched_pathways_by_sample_select_sample"]],
    input[["enriched_pathways_by_sample_select_db"]]
  )
  if ( input[["enriched_pathways_by_sample_select_source"]] == "enrichr" & is.data.frame(sample_data()$enriched_pathways$enrichr$by_sample) ) {
    sample_data()$enriched_pathways$enrichr$by_sample %>%
    dplyr::filter(
      sample == input[["enriched_pathways_by_sample_select_sample"]],
      db == input[["enriched_pathways_by_sample_select_db"]]
    ) %>%
    dplyr::select(3,4,5,6,10,11) %>%
    dplyr::arrange(-Combined.Score) %>%
    dplyr::mutate(
      P.value = formatC(P.value, format = "e", digits = 2),
      Adjusted.P.value = formatC(Adjusted.P.value, format = "e", digits = 2),
      Combined.Score = formatC(Combined.Score, format = "f", digits = 2)
    ) %>%
    dplyr::rename(
      "p-value" = P.value,
      "adj. p-value" = Adjusted.P.value,
      "combined score" = Combined.Score,
    ) %>%
    formattable::formattable(
      list("combined score" = formattable::color_bar("pink"))
    ) %>%
    formattable::as.datatable(
      filter = "top",
      selection = "none",
      escape = FALSE,
      autoHideNavigation = TRUE,
      rownames = FALSE,
      extensions = c("Buttons"),
      class = "cell-border stripe",
      options = list(
        columnDefs = list(list(visible = FALSE, targets = c(2,5))),
        scrollX = TRUE,
        dom = "Bfrtip",
        lengthMenu = c(15, 30, 50, 100),
        pageLength = 15,
        buttons = list(
          "colvis",
          list(
            extend = "collection",
            text = "Download",
            buttons = list(
              list(
                extend = "csv",
                filename = "enriched_pathways_from_enrichr_by_sample",
                title = "Enriched pathways from Enrichr by sample"
              ),
              list(
                extend = "excel",
                filename = "enriched_pathways_from_enrichr_by_sample",
                title = "Enriched pathways from Enrichr by sample"
              )
            )
          )
        )
      )
    ) %>%
    DT::formatStyle(columns = c("combined score"), textAlign = "right")
  } else if ( input[["enriched_pathways_by_sample_select_source"]] == "GSVA" & is.data.frame(sample_data()$enriched_pathways$GSVA$by_sample) ) {
    sample_data()$enriched_pathways$GSVA$by_sample %>%
    dplyr::filter(group == input[["enriched_pathways_by_sample_select_sample"]]) %>%
    dplyr::select(-group) %>%
    dplyr::arrange(q_value) %>%
    dplyr::mutate(
      p_value = formatC(p_value, format = "e", digits = 2),
      q_value = formatC(q_value, format = "e", digits = 2)
    ) %>%
    dplyr::rename(
      "Gene set name" = name,
      "Description" = description,
      "Number of genes" = length,
      "Genes" = genes,
      "Enrichment score" = enrichment_score,
      "p-value" = p_value,
      "adj. p-value" = q_value
    ) %>%
    formattable::formattable() %>%
    formattable::as.datatable(
      filter = "top",
      selection = "none",
      escape = FALSE,
      autoHideNavigation = TRUE,
      rownames = FALSE,
      extensions = c("Buttons"),
      class = "cell-border stripe",
      options = list(
        columnDefs = list(list(visible = FALSE, targets = c(3,4))),
        scrollX = TRUE,
        dom = "Bfrtip",
        lengthMenu = c(15, 30, 50, 100),
        pageLength = 15,
        buttons = list(
          "colvis",
          list(
            extend = "collection",
            text = "Download",
            buttons = list(
              list(
                extend = "csv",
                filename = "enriched_pathways_from_GSVA_by_sample",
                title = "Enriched pathways from GSVA by sample"
              ),
              list(
                extend = "excel",
                filename = "enriched_pathways_from_GSVA_by_sample",
                title = "Enriched pathways from GSVA by sample"
              )
            )
          )
        )
      )
    )
  }
})

# alternative text messages
output[["enriched_pathways_by_sample_table_missing"]] <- renderText({
  "Data not available. Possible reason: Data not generated."
})

output[["enriched_pathways_by_sample_table_no_markers_found"]] <- renderText({
  "No marker genes identified to perform pathway enrichment analysis with."
})

output[["enriched_pathways_by_sample_table_missing_enrichr"]] <- renderText({
  "Data not available. Possible reasons: Only 1 sample in this data set, no marker genes found or data not generated."
})

output[["enriched_pathways_by_sample_table_no_gene_sets_enriched"]] <- renderText({
  "No gene sets were found to be enriched (with the selected statistical thresholds) in any sample."
})

output[["enriched_pathways_by_sample_table_only_one_sample_in_data_set"]] <- renderText({
  "The loaded data set consists of a single sample which means GSVA cannot be applied."
})

output[["enriched_pathways_by_sample_table_missing_gsva"]] <- renderText({
  "Data not available. Possible reason: Data not generated."
})

# info box
observeEvent(input[["enriched_pathways_by_sample_info"]], {
  showModal(
    modalDialog(
      enriched_pathways_by_sample_info[["text"]],
      title = enriched_pathways_by_sample_info[["title"]],
      easyClose = TRUE,
      footer = NULL
    )
  )
})
```

```{r}

shinydashboard::tabItem(tabName = , <details>)
shiny::uiOutput(outputId = )

##in tab, have option for gene id conversion
tab_stringdb <- shinydashboard::tabItem(
  tabName = "STRINGdb",
  #tab contents 1
  box(
    title = title,
    status = "primary",
    solidHeader = TRUE,
    width = 12,
    collapsible = TRUE,
    tagList(
      uiOutput("todo"),
      uiOutput("stringdb_UI")
      )
    )
  )

tab_msigdb <- shinydashboard::tabItem(
  tabName = "MSigDB",
  #tab contents 1
  box(
    title = title,
    status = "primary",
    solidHeader = TRUE,
    width = 12,
    collapsible = TRUE,
    tagList(
      uiOutput("enriched_pathways_by_cluster_select_source_UI"),
      uiOutput("enriched_pathways_by_cluster_UI")
      )
    )
  )

```

```{r}

ui <- dashboardPage(
  dashboardHeader(
    title = span("Gene-Set Viz ", style = "color: white; font-size: 28px; font-weight: bold")
  ),
  dashboardSidebar(
    tags$head(tags$style(HTML(".content-wrapper {overflow-x: scroll;}"))),
    sidebarMenu(
      sidebarMenuOutput("sidebar_menu")
    )
  ),
  dashboardBody(
    tags$script(HTML('$("body").addClass("fixed");')),
    tabItems(
      tab_stringdb,
      tab_msigdb,
    )
  )
)
```

##shiny_server.R
```{r}
##----------------------------------------------------------------------------##
##
##----------------------------------------------------------------------------##
server <- function(input, output, session) {

  ##--------------------------------------------------------------------------##
  ## Color management.
  ##--------------------------------------------------------------------------##
  # Dutch palette from flatuicolors.com
  colorset_dutch <- c(
    "#FFC312","#C4E538","#12CBC4","#FDA7DF","#ED4C67",
    "#F79F1F","#A3CB38","#1289A7","#D980FA","#B53471",
    "#EE5A24","#009432","#0652DD","#9980FA","#833471",
    "#EA2027","#006266","#1B1464","#5758BB","#6F1E51"
  )

  # Spanish palette from flatuicolors.com
  colorset_spanish <- c(
    "#40407a","#706fd3","#f7f1e3","#34ace0","#33d9b2",
    "#2c2c54","#474787","#aaa69d","#227093","#218c74",
    "#ff5252","#ff793f","#d1ccc0","#ffb142","#ffda79",
    "#b33939","#cd6133","#84817a","#cc8e35","#ccae62"
  )

  default_colorset <- c(colorset_dutch, colorset_spanish)

  cell_cycle_colorset <- setNames(
    c("#45aaf2", "#f1c40f", "#e74c3c", "#7f8c8d"),
    c("G1",      "S",       "G2M",     "-")
  )

  ##--------------------------------------------------------------------------##
  ## Central parameters.
  ##--------------------------------------------------------------------------##
  scatter_plot_dot_size <- list(
    min = 1,
    max = 20,
    step = 1,
    default = 5
  )

  scatter_plot_dot_opacity <- list(
    min = 0.1,
    max = 1.0,
    step = 0.1,
    default = 1.0
  )

  scatter_plot_percentage_cells_to_show <- list(
    min = 10,
    max = 100,
    step = 10,
    default = 100
  )

  preferences <- reactiveValues(use_webgl = TRUE)

  ##--------------------------------------------------------------------------##
  ## Sidebar menu.
  ##--------------------------------------------------------------------------##
  output[["sidebar_menu"]] <- renderMenu({
    sidebarMenu(id = "sidebar",
      menuItem(
        "Load data", tabName = "loadData",
        icon = icon("spinner"), selected = TRUE
      ),
      menuItem(
        "Overview", tabName = "overview",
        icon = icon("binoculars")
      ),
      menuItem(
        "Samples", tabName = "samples",
        icon = icon("star")
      ),
      menuItem(
        "Clusters", tabName = "clusters",
        icon = icon("braille")
      ),
      menuItem(
        "Most expressed genes", tabName = "mostExpressedGenes",
        icon = icon("bullhorn")
      ),
      menuItem(
        "Marker genes", tabName = "markerGenes",
        icon = icon("magnet")
      ),
      menuItem(
        "Enriched pathways", tabName = "enrichedPathways",
        icon = icon("sitemap")
      ),
      menuItem(
        "Gene expression", tabName = "geneExpression",
        icon = icon("signal")
      ),
      menuItem(
        "Gene set expression", tabName = "geneSetExpression",
        icon = icon("list")
      ),
      menuItem(
        "Trajectory", tabName = "trajectory",
        icon = icon("random")
      ),
      menuItem(
        "Gene ID conversion", tabName = "geneIdConversion",
        icon = icon("barcode")
      ),
      menuItem(
        "Analysis info", tabName = "info",
        icon = icon("info")
      ),
      menuItem(
        "Color management", tabName = "color_management",
        icon = icon("palette")
      ),
      menuItem(
        "About", tabName = "about",
        icon = icon("at")
      )
    )
  })

  ##--------------------------------------------------------------------------##
  ## Sample data.
  ##--------------------------------------------------------------------------##
  sample_data <- reactive({
    if ( is.null(input[["input_file"]]) || is.na(input[["input_file"]]) ) {
      sample_data <- readRDS(
        system.file("extdata/v1.2/example.rds", package = "cerebroApp")
      )
    } else {
      req(input[["input_file"]])
      sample_data <- readRDS(input[["input_file"]]$datapath)
    }
    # get list of sample names
    if ( is.factor(sample_data$cells$sample) ) {
      sample_data$sample_names <- levels(sample_data$cells$sample)
    } else {
      sample_data$sample_names <- sample_data$cells$sample %>% unique()
    }
    # get list of cluster names
    if ( is.factor(sample_data$cells$cluster) ) {
      sample_data$cluster_names <- levels(sample_data$cells$cluster)
    } else {
      sample_data$cluster_names <- sample_data$cells$cluster %>% unique() %>% sort()
    }
    sample_data
  })

  ##--------------------------------------------------------------------------##
  ## Function to calculate A-by-B tables (e.g. samples by clusters).
  ##--------------------------------------------------------------------------##
  calculateTableAB <- function(groupA, groupB) {
    # check if specified group columns exist in meta data
    if ( groupA %in% colnames(sample_data()$cells) == FALSE ) {
      stop(paste0("Column specified as groupA (`", groupA, "`) could not be found in meta data."), call. = FALSE)
    }
    if ( groupB %in% colnames(sample_data()$cells) == FALSE ) {
      stop(paste0("Column specified as groupB (`", groupB, "`) could not be found in meta data."), call. = FALSE)
    }
    table <- sample_data()$cells[,c(groupA,groupB)]
    # factorize group columns A and B if not already a factor
    if ( is.character(table[,groupA]) ) {
      table[[,groupA]] <- factor(
        table[[,groupA]],
        levels = table[[,groupA]] %>% unique() %>% sort()
      )
    }
    if ( is.character(table[,groupB]) ) {
      table[[,groupB]] <- factor(
        table[[,groupB]],
        levels = table[[,groupB]] %>% unique() %>% sort()
      )
    }
    # generate table
    table <- table %>%
      dplyr::group_by_at(c(groupA,groupB)) %>%
      dplyr::summarize(count = dplyr::n()) %>%
      tidyr::spread(`groupB`, count, fill = 0) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(total_cell_count = rowSums(.[c(2:ncol(.))])) %>%
      dplyr::select(c(`groupA`, 'total_cell_count', dplyr::everything()))
    # fix order of columns if cell cycle info was chosen as second group
    if ( 'G1' %in% colnames(table) && 'G2M' %in% colnames(table) && 'S' %in% colnames(table) ) {
      table <- table %>%
        dplyr::select(c(`groupA`, 'total_cell_count', 'G1', 'S', 'G2M', dplyr::everything()))
    }
    # return
    return(table)
  }

  ##--------------------------------------------------------------------------##
  ## Colors for samples and clusters.
  ##--------------------------------------------------------------------------##
  reactive_colors <- reactive({
    colors <- list()

    # grab sample-specific colors from input file if it exists, otherwise take
    # default colorset
    if ( !is.null(sample_data()$samples$colors) ) {
      colors$samples <- sample_data()$samples$colors
    } else {
      colors$samples <- default_colorset[1:length(sample_data()$sample_names)]
      names(colors$samples) <- sample_data()$sample_names
    }
    # assign respective color picker in "Color management" tab to each sample
    if ( !is.null(input[[paste0('color_sample_', levels(sample_data()$cells$sample)[1])]]) ) {
      for ( i in 1:length(colors$samples) ) {
        colors$samples[i] <- input[[paste0('color_sample_', levels(sample_data()$cells$sample)[i])]]
      }
    }

    # grab cluster-specific colors from input file if it exists, otherwise take
    # default colorset
    if ( !is.null(sample_data()$clusters$colors) ) {
      colors$clusters <- sample_data()$clusters$colors
    } else {
      colors$clusters <- default_colorset[1:length(sample_data()$cluster_names)]
      names(colors$clusters) <- sample_data()$cluster_names
    }
    # assign respective color picker in "Color management" tab to each cluster
    if ( !is.null(input[[paste0('color_cluster_', levels(sample_data()$cells$cluster)[1])]]) ) {
      for ( i in 1:length(colors$clusters) ) {
        colors$clusters[i] <- input[[paste0('color_cluster_', levels(sample_data()$cells$cluster)[i])]]
      }
    }

    return(colors)
  })

  ##--------------------------------------------------------------------------##
  ## Tabs.
  ##--------------------------------------------------------------------------##
  source(system.file("shiny/v1.2/load_data/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/overview/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/samples/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/clusters/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/most_expressed_genes/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/marker_genes/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/enriched_pathways/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/gene_expression/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/gene_set_expression/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/gene_id_conversion/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/trajectory/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/analysis_info/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/color_management/server.R", package = "cerebroApp"), local = TRUE)
  source(system.file("shiny/v1.2/about/server.R", package = "cerebroApp"), local = TRUE)

}
```

##shiny_UI.R
```{r}
##----------------------------------------------------------------------------##
## Custom functions.
##----------------------------------------------------------------------------##
cerebroBox <- function(title, content) {
  box(
    title = title,
    status = "primary",
    solidHeader = TRUE,
    width = 12,
    collapsible = TRUE,
    content
  )
}

cerebroInfoButton <- function(id) {
  actionButton(
    inputId = id,
    label = "info",
    icon = NULL,
    class = "btn-xs",
    title = "Show additional information for this panel."
  )
}

boxTitle <- function(title) {
  p(title, style = "padding-right: 5px; display: inline")
}

##----------------------------------------------------------------------------##
##
##----------------------------------------------------------------------------##
source(system.file("shiny/v1.2/load_data/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/overview/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/samples/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/clusters/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/most_expressed_genes/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/marker_genes/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/enriched_pathways/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/gene_expression/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/gene_set_expression/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/trajectory/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/gene_id_conversion/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/analysis_info/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/color_management/UI.R", package = "cerebroApp"), local = TRUE)
source(system.file("shiny/v1.2/about/UI.R", package = "cerebroApp"), local = TRUE)

##----------------------------------------------------------------------------##
##
##----------------------------------------------------------------------------##
ui <- dashboardPage(
  dashboardHeader(
    title = span("Cerebro ", style = "color: white; font-size: 28px; font-weight: bold")
  ),
  dashboardSidebar(
    tags$head(tags$style(HTML(".content-wrapper {overflow-x: scroll;}"))),
    sidebarMenu(
      sidebarMenuOutput("sidebar_menu")
    )
  ),
  dashboardBody(
    tags$script(HTML('$("body").addClass("fixed");')),
    tabItems(
      tab_load_data,
      tab_overview,
      tab_samples,
      tab_clusters,
      tab_most_expressed_genes,
      tab_marker_genes,
      tab_enriched_pathways,
      tab_gene_expression,
      tab_gene_set_expression,
      tab_trajectory,
      tab_gene_id_conversion,
      tab_analysis_info,
      tab_color_management,
      tab_about
    )
  )
)
```

##notes
ERROR: cannot coerce type 'closure' to vector of type 'character'
box(
    title = title
changed to:
box(
    title = "STRING"...
    
    
- box(), fluidRow(), 
- fileInput(), uiOutput()
--use tagList() to combine multiple. e.g: tagList(fileInput(), uiOutput(), uiOutput()...)