app <- ShinyDriver$new("../../")
app$snapshotInit("basicTest")

app$setInputs(demo1 = "click")
app$setInputs(submit = "click")
app$snapshot()
app$setInputs(sidebar = "stringdb")
app$setInputs(runstringdb_button = "click")
app$snapshot()
app$setInputs(sidebar = "msigdb")
app$setInputs(msigdb_category_input = "C7")
app$setInputs(runmsigdb_button = "click")
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(sidebar = "reactome")
app$setInputs(runreactome_button = "click")
app$snapshot()
app$snapshot()
app$setInputs(sidebar = "david")
app$setInputs(sidebar = "dose")
app$setInputs(rundose_button = "click")
app$snapshot()
app$setInputs(sidebar = "ncg")
app$setInputs(runncg_button = "click")
app$snapshot()
app$setInputs(sidebar = "dgn")
app$snapshot()
app$setInputs(rundgn_button = "click")
app$snapshot()
app$setInputs(sidebar = "enrichr")
app$setInputs(enrichr_db = "Genome_Browser_PWMs")
app$setInputs(runenrichr_button = "click")
app$snapshot()
