# See: https://community.rstudio.com/t/deploying-shiny-app-with-github-actions/78436/3
name: deploy-shiny
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect"), type = "binary")
        shell: Rscript {0}
      - name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='bimberlab', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp('inst/app', appName = 'geneSetVis', forceUpdate = TRUE)"