# See: https://community.rstudio.com/t/deploying-shiny-app-with-github-actions/78436/3
name: deploy-shiny
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master

      - name: Install packages
        run: |          
          sudo apt-get update && sudo apt-get install -yq libcurl4-openssl-dev openjdk-11-jdk

      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect", "remotes"))
        shell: Rscript {0}

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Install dependencies, Linux
        if: runner.os != 'Windows'
        run: |
          remotes::install_deps(dependencies = TRUE, upgrade = "always")
        shell: Rscript {0}

      - name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='bimberlab', token='${{secrets.SHINYAPPS_TOKEN}}', secret='${{secrets.SHINYAPPS_SECRET}}')"
          Rscript -e "rsconnect::deployApp('inst/app', appName = 'geneSetVis', forceUpdate = TRUE)"
